/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlgorithmFullViewCard: typeof import('./src/components/user/algorithm/AlgorithmFullViewCard.vue')['default']
    AlgorithmManager: typeof import('./src/components/user/algorithm/AlgorithmManager.vue')['default']
    AlgorithmMenu: typeof import('./src/components/user/dashboard/AlgorithmMenu.vue')['default']
    AlgorithmMenuCard: typeof import('./src/components/user/dashboard/AlgorithmMenuCard.vue')['default']
    AlgorithmSimpleViewCard: typeof import('./src/components/user/algorithm/AlgorithmSimpleViewCard.vue')['default']
    AuthenticationForm: typeof import('./src/components/user/authentication/AuthenticationForm.vue')['default']
    AwesomePopup: typeof import('./src/components/utility/AwesomePopup.vue')['default']
    AwesomeSlider: typeof import('./src/components/utility/slider/AwesomeSlider.vue')['default']
    AwesomeSliderPresentationBar: typeof import('./src/components/utility/slider/AwesomeSliderPresentationBar.vue')['default']
    CodeEditor: typeof import('./src/components/editor/CodeEditor.vue')['default']
    CodeEditorNavigation: typeof import('./src/components/editor/CodeEditorNavigation.vue')['default']
    ComponentRenderer: typeof import('./src/components/visualizer/graph/ComponentRenderer.vue')['default']
    DeleteAlgorithmPopUp: typeof import('./src/components/user/algorithm/DeleteAlgorithmPopUp.vue')['default']
    DialogClose: typeof import('radix-vue')['DialogClose']
    DialogContent: typeof import('radix-vue')['DialogContent']
    DialogDescription: typeof import('radix-vue')['DialogDescription']
    DialogOverlay: typeof import('radix-vue')['DialogOverlay']
    DialogPortal: typeof import('radix-vue')['DialogPortal']
    DialogRoot: typeof import('radix-vue')['DialogRoot']
    DialogTitle: typeof import('radix-vue')['DialogTitle']
    DialogTrigger: typeof import('radix-vue')['DialogTrigger']
    ErrorBoundary: typeof import('./src/components/ErrorBoundary.vue')['default']
    FeaturedAlgorithms: typeof import('./src/components/user/dashboard/FeaturedAlgorithms.vue')['default']
    GraphEdge: typeof import('./src/components/visualizer/graph/GraphEdge.vue')['default']
    GraphNode: typeof import('./src/components/visualizer/graph/GraphNode.vue')['default']
    Grift: typeof import('./src/components/visualizer/grift/Grift.vue')['default']
    IconButton: typeof import('./src/components/utility/iconButton/IconButton.vue')['default']
    Label: typeof import('radix-vue')['Label']
    MarkFavouriteButton: typeof import('./src/components/user/algorithm/MarkFavouriteButton.vue')['default']
    MockButton: typeof import('./src/components/mock/sfc/MockButton.vue')['default']
    MockComponent: typeof import('./src/components/mock/sfc/MockComponent.vue')['default']
    MockFooter: typeof import('./src/components/mock/sfc/MockFooter.vue')['default']
    MockHeader: typeof import('./src/components/mock/sfc/MockHeader.vue')['default']
    NavSidebar: typeof import('./src/components/NavSidebar.vue')['default']
    PopoverArrow: typeof import('radix-vue')['PopoverArrow']
    PopoverClose: typeof import('radix-vue')['PopoverClose']
    PopoverContent: typeof import('radix-vue')['PopoverContent']
    PopoverPortal: typeof import('radix-vue')['PopoverPortal']
    PopoverRoot: typeof import('radix-vue')['PopoverRoot']
    PopoverTrigger: typeof import('radix-vue')['PopoverTrigger']
    PrettyText: typeof import('./src/components/utility/text/PrettyText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveAlgorithmModal: typeof import('./src/components/utility/SaveAlgorithmModal.vue')['default']
    SaveAlgorithmPopup: typeof import('./src/components/user/algorithm/SaveAlgorithmPopup.vue')['default']
    Searchbar: typeof import('./src/components/user/dashboard/Searchbar.vue')['default']
    SearchResultsList: typeof import('./src/components/user/dashboard/SearchResultsList.vue')['default']
    SearchResultsListCard: typeof import('./src/components/user/dashboard/SearchResultsListCard.vue')['default']
    SelectionModal: typeof import('./src/components/utility/SelectionModal.vue')['default']
    SignInForm: typeof import('./src/components/user/authentication/SignInForm.vue')['default']
    SimpleMessagePopup: typeof import('./src/components/utility/SimpleMessagePopup.vue')['default']
    UserDashboard: typeof import('./src/components/user/dashboard/UserDashboard.vue')['default']
    UserProfile: typeof import('./src/components/user/dashboard/UserProfile.vue')['default']
    Visualizer: typeof import('./src/components/visualizer/Visualizer.vue')['default']
    VisualizerConsole: typeof import('./src/components/visualizer/VisualizerConsole.vue')['default']
    VisualizerNavigation: typeof import('./src/components/visualizer/VisualizerNavigation.vue')['default']
  }
}
