/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AwesomePopup: typeof import('./src/components/utility/AwesomePopup.vue')['default']
    AwesomeSlider: typeof import('./src/components/utility/slider/AwesomeSlider.vue')['default']
    AwesomeSliderPresentationBar: typeof import('./src/components/utility/slider/AwesomeSliderPresentationBar.vue')['default']
    CodeEditor: typeof import('./src/components/editor/CodeEditor.vue')['default']
    CodeEditorNavigation: typeof import('./src/components/editor/CodeEditorNavigation.vue')['default']
    ComponentRenderer: typeof import('./src/components/visualizer/graph/ComponentRenderer.vue')['default']
    ErrorBoundary: typeof import('./src/components/ErrorBoundary.vue')['default']
    GraphEdge: typeof import('./src/components/visualizer/graph/GraphEdge.vue')['default']
    GraphNode: typeof import('./src/components/visualizer/graph/GraphNode.vue')['default']
    Grift: typeof import('./src/components/visualizer/grift/Grift.vue')['default']
    IconButton: typeof import('./src/components/utility/iconButton/IconButton.vue')['default']
    LoadingCard: typeof import('./src/components/visualizer/grift/LoadingCard.vue')['default']
    MockButton: typeof import('./src/components/mock/sfc/MockButton.vue')['default']
    MockComponent: typeof import('./src/components/mock/sfc/MockComponent.vue')['default']
    MockFooter: typeof import('./src/components/mock/sfc/MockFooter.vue')['default']
    MockHeader: typeof import('./src/components/mock/sfc/MockHeader.vue')['default']
    NavSidebar: typeof import('./src/components/NavSidebar.vue')['default']
    Playback: typeof import('./src/components/visualizer/playback/Playback.vue')['default']
    PrettyText: typeof import('./src/components/utility/text/PrettyText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveAlgorithmModal: typeof import('./src/components/utility/SaveAlgorithmModal.vue')['default']
    SelectionModal: typeof import('./src/components/utility/SelectionModal.vue')['default']
    SimpleMessagePopup: typeof import('./src/components/utility/SimpleMessagePopup.vue')['default']
    ToastAction: typeof import('radix-vue')['ToastAction']
    ToastViewport: typeof import('radix-vue')['ToastViewport']
    Visualizer: typeof import('./src/components/visualizer/Visualizer.vue')['default']
    VisualizerConsole: typeof import('./src/components/visualizer/VisualizerConsole.vue')['default']
    VisualizerNavigation: typeof import('./src/components/visualizer/VisualizerNavigation.vue')['default']
  }
}
